src/adapters/in_memory.rs
src/main.rs

20 letters String→ at least 20bytes 
Struct { u64, u32 } → 8 + 4 + Padding? = around 12 bytes 🤩

Change String to Struct with u64,u32

---

src/config.rs
src/handlers.rs
src/main.rs
src/protocol/command.rs
src/protocol/mod.rs
src/test.rs

Perhaps, dynamic configuration setting is required.

feature : config set applied 

---

src/adapters/persistence/size_encoding.rs

It was actually integer parsing
- rename `size_encode` to `data_encode` (temporary)
- add `integer_decode`
- add integer encoding part

Add Integer Encoding

---

src/adapters/persistence/bytes_handler.rs
src/adapters/persistence/data_encoder.rs
src/adapters/persistence/mod.rs
src/services/statefuls/routers/inmemory_router.rs

use of `context`, error simplified

feat: error handler

---

src/adapters/persistence/bytes_handler.rs
src/adapters/persistence/data_encoder.rs
src/services/statefuls/routers/inmemory_router.rs

Instead of using drain which will cost O(n) for shifting, lifetime inner data handling is implemented.

Optimization: zero memory shift decoding

---

src/adapters/controller/mod.rs
src/adapters/persistence/byte_decoder.rs
src/adapters/persistence/mod.rs
src/config.rs
src/main.rs
src/services/config_handler/mod.rs
src/services/mod.rs
src/services/query_io.rs
src/services/statefuls/mod.rs
src/services/statefuls/routers/cache_actor.rs
src/services/statefuls/routers/cache_dispatcher.rs
src/services/statefuls/routers/mod.rs
src/services/statefuls/routers/ttl_actor.rs
src/services/statefuls/ttl_handlers/mod.rs
src/test.rs

feat: cache expiry 

---

src/config.rs

declarative macro applied to allow for set of default values and injectable values.

feat: port configuration

---

src/adapters/persistence/byte_encoder.rs
src/config.rs
src/services/mod.rs
src/services/query_manager/mod.rs
src/services/query_manager/query_io.rs
src/services/query_manager/request.rs
src/services/statefuls/routers/cache_manager.rs
src/test.rs

feat: replication info 

---

src/adapters/persistence/byte_encoder.rs
src/adapters/persistence/decoder/builder.rs
src/adapters/persistence/decoder/byte_decoder.rs
src/adapters/persistence/decoder/mod.rs
src/adapters/persistence/decoder/states.rs
src/adapters/persistence/encoder/byte_encoder.rs
src/adapters/persistence/encoder/mod.rs
src/adapters/persistence/mod.rs
src/main.rs
src/services/query_manager/mod.rs
src/services/statefuls/mod.rs
src/services/statefuls/persistence_models/mod.rs
src/services/statefuls/routers/cache_manager.rs
src/services/statefuls/routers/interfaces.rs
src/services/statefuls/routers/mod.rs
src/services/statefuls/routers/save_actor.rs
src/services/statefuls/routers/ttl_manager.rs
src/test.rs

backlog: dependency inversion between encoder and service handler cc. @echo724

refactor: after save operation

---

src/adapters/persistence/decoder/mod.rs
src/adapters/persistence/mod.rs
src/main.rs
src/test.rs
tests/test_set_get.rs

`EnDecoder` is simple unit struct that wraps behaviours, namely decoding and encoding.

decoder -> endecoder, hirarchy change

---

src/adapters/persistence/decoder/mod.rs
src/adapters/persistence/mod.rs
src/lib.rs
src/services/interfaces/endec.rs
src/services/interfaces/mod.rs
src/services/mod.rs
src/services/query_manager/mod.rs
src/services/statefuls/routers/cache_manager.rs
src/services/statefuls/routers/mod.rs
src/services/statefuls/routers/ttl_manager.rs

to stick to DRY, marker trait is added

chore: add thread safe cloneable trait

---

src/config.rs
tests/common.rs
tests/test_cancellation_token.rs
tests/test_config_get_dir.rs
tests/test_keys.rs
tests/test_replication_info.rs
tests/test_save_read_dump.rs
tests/test_set_get.rs

test: explicit test build

---

src/lib.rs
src/main.rs
src/services/config/command.rs
src/services/config/config_actor.rs
src/services/config/config_manager.rs
src/services/config/macros.rs
src/services/config/mod.rs
tests/common.rs
tests/test_save_read_dump.rs

closes #104 
partially related to #8 #7

feat: immuts values on config manager

---

src/adapters/io/tokio_stream.rs
src/services/cluster/actor.rs
src/services/cluster/command.rs
src/services/cluster/manager.rs
src/services/stream_manager/interface.rs
tests/common.rs

feat: add peer & heartbeat

---

scripts.sh
src/adapters/io/tokio_stream.rs
src/lib.rs
src/services/cluster/inbound_mode.rs
src/services/cluster/manager.rs
src/services/cluster/master_mode.rs
src/services/cluster/mod.rs
src/services/cluster/outbound_mode.rs
src/services/config/actor.rs
src/services/config/manager.rs
src/services/config/replication.rs
src/services/statefuls/persist/actor.rs
src/services/stream_manager/interface.rs
src/services/stream_manager/mod.rs
src/services/stream_manager/query_io.rs
src/services/stream_manager/request_controller/replica/arguments.rs
src/services/stream_manager/request_controller/replica/replication_request.rs
tests/common.rs
tests/test_handshake.rs

feat: outbound three-way handshake

---

Cargo.toml
src/lib.rs
src/main.rs
src/services/cluster/manager.rs
src/services/cluster/outbound_mode.rs
src/services/config/actor.rs
src/services/config/manager.rs
tests/common.rs
tests/test_disseminate_peers.rs
tests/test_handshake.rs
tests/test_heartbeat.rs
tests/test_heartbeat_broadcasting.rs

feat: replica mode conversion

---

README.md
diagrams/client_query.mmd
diagrams/clustering.mmd
tests/common.rs

sequence diagram for client request controlling added

doc: client query sequence diagram

---

src/adapters/io/tokio_stream.rs
src/services/cluster/actor.rs
src/services/cluster/command.rs
src/services/cluster/manager.rs

- Kill switch on peer listener
- Retrieving killed peer listner
- refactoring on cluster actor/manager

feat: peer listener

---

src/services/cluster/actors/listening_actor.rs
src/services/cluster/actors/mod.rs
src/services/cluster/actors/peer.rs
src/services/cluster/outbound/stream.rs
src/services/query_io.rs
src/services/statefuls/persist/mod.rs

closes #167 
Although entire data structure has not be settled yet, this pr outlines how we can possibly transfer rather a complex data structure with custom serde.

feat: peer state serde

---

src/main.rs
src/services/client/stream.rs
src/services/cluster/inbound/request.rs
src/services/query_io.rs

context-based unpacking logic based on generics implemented

feat: generify unpack

---

src/services/client/stream.rs
src/services/query_io.rs

Remove implicit lowercasing from query extraction

fix: remove lowercasing 

---

src/services/cluster/actors/actor.rs
src/services/cluster/actors/command.rs
src/services/cluster/actors/listening_actor.rs
src/services/cluster/manager.rs
src/services/cluster/outbound/stream.rs
tests/test_heartbeat.rs

feat: sharing peer state among peers

---

src/services/client/manager.rs
src/services/client/request.rs
src/services/client/stream.rs
src/services/cluster/actors/actor.rs
src/services/cluster/actors/command.rs
src/services/cluster/actors/replication.rs
src/services/cluster/inbound/stream.rs
src/services/cluster/manager.rs
src/services/cluster/outbound/stream.rs
tests/test_clustering.rs
tests/test_heartbeat.rs

feat: cluster info client query and node connection check

---

src/services/cluster/actors/replication.rs
src/services/query_io.rs

to enable gossip mechanism, we need to have hop count so the system can make good prediction.

feat: preliminary step for gossip - hop count

---

src/services/cluster/actors/actor.rs
src/services/cluster/actors/listening_actor.rs
src/services/cluster/actors/peer.rs
src/services/cluster/actors/replication.rs
src/services/cluster/manager.rs
src/services/cluster/outbound/stream.rs
tests/test_clustering.rs
tests/test_heartbeat.rs

feat: logarithmic hop count calculator

---

src/services/cluster/actors/listening_actor.rs

Common interest can be shared regardless of type of stream.

refactor: extract report liveness

---

scripts.sh
src/adapters/io/tokio_stream.rs
src/lib.rs
src/services/cluster/actors/actor.rs
src/services/cluster/actors/listening_actor.rs
src/services/cluster/actors/replication.rs
src/services/cluster/actors/types.rs
src/services/cluster/inbound/stream.rs
src/services/cluster/manager.rs
src/services/cluster/outbound/stream.rs
src/services/config/init.rs
src/services/query_io.rs
tests/common.rs
tests/test_clustering.rs
tests/test_disseminate_peers.rs
tests/test_handshake.rs
tests/test_heartbeat.rs
tests/test_replication_info.rs
tests/test_save_read_dump.rs

test: check_internodes_communication

---

README.md

As gossip algorithm has been implemented, readme contents are added.

doc: gossip added

---

src/services/client/manager.rs
src/services/client/request.rs
src/services/client/stream.rs
src/services/cluster/actors/actor.rs
src/services/cluster/actors/command.rs
src/services/cluster/actors/mod.rs
src/services/cluster/manager.rs
tests/test_cluster_forget.rs

feat: cluster forget command operation

---

src/services/cluster/peers/address.rs
tests/common.rs
tests/test_cluster_forget.rs

test: cluster-wide forget operation propagation

---

scripts.sh
src/client_utils/mod.rs
src/services/cluster/actors/actor.rs
src/services/cluster/peers/identifier.rs

feat: recovery connection on reconnection

---

src/adapters/aof/local_aof.rs
src/services/aof.rs
src/services/client/manager.rs
src/services/client/request.rs
src/services/cluster/actors/actor.rs
src/services/cluster/command/cluster_command.rs
src/services/query_io.rs

integrate log with services resolves #153 
write operation integrated with `QueryIO` resolves #152

feat: operation log

---

src/adapters/aof/local_aof.rs
src/services/aof.rs
src/services/client/manager.rs
src/services/cluster/actors/actor.rs
src/services/cluster/command/cluster_command.rs
src/services/query_io.rs

- shorten the lifetime of bytes
- conversion logic moved to writeRequest

refactor: set convertor moved to write request

---

src/services/client/manager.rs
src/services/statefuls/snapshot/save/actor.rs
tests/test_save_read_dump.rs

This pull request includes the following changes:
- Fixed the save dump test to ensure it passes correctly.
- Corrected the file write logic to improve functionality.

fix: save target to file

---

src/services/aof.rs
src/services/cluster/actors/actor.rs
src/services/cluster/actors/listening_actor.rs
src/services/cluster/command/cluster_command.rs
src/services/cluster/command/listening_command.rs
src/services/cluster/replications/replication.rs
src/services/query_io.rs

`WriteOperation` became a part of logging 
#157

feat: append entry for logging

---

src/adapters/io/tokio_stream.rs
src/services/cluster/actors/actor.rs
src/services/cluster/actors/listening_actor.rs
src/services/cluster/command/cluster_command.rs
src/services/cluster/command/listening_command.rs
src/services/cluster/peers/peer.rs
src/services/cluster/replications/replication.rs
src/services/interface.rs
src/services/query_io.rs

#157 
- Fix serialization bug
- renaming 
- add test cases for serde
Now, replicas receive entries.

feat: consensus logging outlined

---

src/client_utils/mod.rs
src/presentation/client_in/manager.rs
src/presentation/cluster_in/communication_manager.rs
src/presentation/cluster_in/peer_listeners/peer_listener.rs
src/presentation/cluster_in/peer_listeners/requests.rs
src/services/cluster/actors/actor.rs
src/services/cluster/actors/commands.rs
src/services/cluster/actors/consensus.rs
src/services/cluster/actors/mod.rs
src/services/cluster/replications/replication.rs
src/services/query_io.rs
tests/test_config_get_dir.rs

- ReqConsensus : consensus_con
- VoteConsensus : to handle follower votes
- `replicas` methods

feat: raft happy path

---

src/domains/cluster_actors/actor.rs
tests/common.rs
tests/test_cluster_forget_node_propagation.rs
tests/test_clustering.rs
tests/test_disseminate_peers.rs
tests/test_heartbeat.rs
tests/test_raft_happy_case.rs
tests/test_recv_full_sync.rs

- raft test case
- optimize the test

test : raft happy case added

---

src/domains/cluster_actors/actor.rs
src/domains/cluster_actors/commands.rs
src/domains/cluster_actors/consensus.rs
src/domains/cluster_actors/replication.rs
src/domains/cluster_listeners/mod.rs
src/presentation/clients/controller.rs
src/presentation/listeners/leader.rs
src/services/handlers/cluster.rs
tests/test_raft_happy_case.rs

feat: AcceptLeaderHeartBeat

---

src/domains/query_parsers/mod.rs
src/domains/query_parsers/parsing_context.rs
src/domains/query_parsers/query_io.rs
tests/test_cluster_known_nodes_increase_when_new_replica_is_added.rs
tests/test_removes_node_when_heartbeat_is_not_received_for_certain_time.rs

- single buffer allocation
- ease of use

optimization: parsing

---

src/adapters/aof/local_aof.rs
src/domains/append_only_files/interfaces.rs
src/domains/append_only_files/log.rs
src/domains/append_only_files/logger.rs
src/domains/caches/cache_manager.rs
src/domains/cluster_actors/actor.rs
src/domains/cluster_actors/replication.rs
src/domains/query_parsers/query_io.rs
src/lib.rs
src/presentation/clients/controllers/handler.rs
src/services/handlers/cluster.rs
tests/test_raft_happy_case.rs

`change_state` that updates the state machine outlined with documentation
log index and commit index were articulated

feat: follower state change outlined

---

src/adapters/aof/local_aof.rs
src/adapters/aof/memory_aof.rs
src/adapters/aof/mod.rs
src/domains/append_only_files/interfaces.rs
src/domains/append_only_files/log.rs
src/domains/append_only_files/logger.rs
src/domains/caches/cache_manager.rs
src/domains/caches/command.rs
src/domains/cluster_actors/actor.rs
src/init.rs
src/main.rs
src/services/handlers/cluster.rs
tests/common.rs

- in memory aof implemenation mainly for testing. 
- replication with in memory aof 
- commit index management
resolves #162 
resolves #157 
resolves #156 
resolved #8

feat: inmemory aof impl

---

diagrams/full_sync_scenario_snapshot.mmd
diagrams/full_sync_scenario_with_append_entry.mmd
diagrams/full_sync_when_commit_was_made.mmd
diagrams/partial_sync.mmd
diagrams/partial_sync_scenario_with_followers.mmd
src/domains/cluster_actors/commands.rs
src/domains/saves/snapshot/snapshot_applier.rs
src/lib.rs
src/presentation/cluster_in/connection_manager.rs
src/presentation/cluster_in/inbound/stream.rs
src/presentation/cluster_in/outbound/stream.rs
src/services/handlers/cluster.rs

This pull request includes the following commits:
- **docs:** Add Full Sync flow diagrams
- **feat:** Replace `commit_idx` from snapshot
- **refactor:** Rename `offset` to `commit_idx`
- **enhancement:** Modify full sync case

feat: replace-current-commit_idx-from-dump

---

src/adapters/aof/local_aof.rs
src/adapters/aof/memory_aof.rs
src/domains/append_only_files/interfaces.rs
src/domains/append_only_files/logger.rs
src/domains/cluster_actors/actor.rs
src/domains/cluster_actors/replication.rs
src/services/handlers/cluster.rs

feat: follower 

---

src/domains/cluster_actors/actor.rs
src/lib.rs
src/presentation/cluster_in/communication_manager.rs
src/services/handlers/cluster.rs

Temporal coupling detected. Fix made for commit case.

fix: bug fix on commit

---

README.md
diagrams/full_sync_scenario_snapshot.mmd
diagrams/full_sync_scenario_with_append_entry.mmd
diagrams/full_sync_when_commit_was_made.mmd
diagrams/partial_sync.mmd
src/domains/cluster_actors/actor.rs
src/domains/cluster_actors/commands.rs
src/domains/cluster_actors/replication.rs
src/domains/query_parsers/query_io.rs
src/lib.rs
src/presentation/clients/controllers/handler.rs
src/presentation/cluster_in/connection_manager.rs
src/presentation/cluster_in/outbound/stream.rs
src/services/handlers/cluster.rs

commit index -> hwm(high water mark)

rename: commit idx to high water mark

---

src/domains/cluster_actors/actor.rs
src/domains/cluster_listeners/mod.rs
src/domains/peers/connected_types.rs
src/domains/peers/peer.rs

refactor: unnest peer kind

---

src/domains/cluster_actors/commands.rs
src/domains/query_parsers/query_io.rs
src/presentation/clients/controllers/handler.rs
src/presentation/clients/request.rs
src/presentation/clients/stream.rs
src/presentation/cluster_in/communication_manager.rs
src/services/handlers/cluster.rs

feat: cluster nodes client api

---

scripts.sh
src/adapters/io/tokio_stream.rs
src/domains/error.rs
src/presentation/clients/controllers/acceptor.rs
src/presentation/clients/stream.rs
src/presentation/listeners/leader.rs
src/services/interface.rs

fix: close client connection on abrupt disconnection

---

src/domains/append_only_files/log.rs
src/domains/cluster_actors/actor.rs
src/services/handlers/cluster.rs

miscellaneous refactorings:
- update_last_seen accept heartbeat
- `ReceiveHeartBeat` logic more functional
resolved #334

feat: update hwm from leader side

---

.github/workflows/rustfmt.yaml

chore: add github actions for formatting

---

src/domains/cluster_actors/actor.rs
src/domains/peers/peer.rs
src/services/handlers/cluster.rs

feat: remove peer triggers cascade

---

src/domains/append_only_files/logger.rs
src/domains/cluster_actors/actor.rs
src/domains/cluster_actors/commands.rs
src/domains/cluster_actors/consensus.rs
src/domains/cluster_actors/consensus/mod.rs
src/domains/cluster_actors/mod.rs
src/domains/cluster_actors/replication.rs
src/domains/cluster_listeners/mod.rs
src/domains/peers/identifier.rs
src/domains/peers/peer.rs
src/domains/query_parsers/query_io.rs
src/init.rs
src/lib.rs
src/presentation/cluster_in/inbound/stream.rs
src/presentation/listeners/follower.rs
src/presentation/listeners/leader.rs
src/services/handlers/cluster.rs
tests/test_leader_election.rs

Use of callback, the same way we manage write request consensus, 
election vote is tracked and applied. 
resolved #354

feat: leader election

---

src/domains/cluster_actors/actor.rs

feat: follower increases term

---

.config/nextest.toml
src/presentation/cluster_in/outbound/stream.rs

```sh
cargo nextest run
```
@echo724  @dpjungmin  @1kihong

chore: nextest config added

---

src/domains/cluster_actors/actor.rs
src/domains/cluster_actors/commands.rs
src/domains/cluster_actors/heartbeats/heartbeat.rs
src/domains/cluster_actors/heartbeats/scheduler.rs
src/domains/query_parsers/query_io.rs
src/presentation/listeners/mod.rs
src/presentation/listeners/peer_listener.rs
src/services/handlers/cluster.rs

feat: cluster heartbeat / AppendEntry RPC separation

---

src/domains/cluster_actors/actor.rs
src/services/handlers/cluster.rs

feat: replication leader agnostic

---

src/adapters/wal/local_wal.rs
src/adapters/wal/memory_wal.rs
src/domains/append_only_files/interfaces.rs
src/domains/append_only_files/log.rs
src/domains/append_only_files/logger.rs
src/domains/cluster_actors/actor.rs
src/domains/cluster_actors/commands.rs
src/domains/cluster_actors/consensus/mod.rs
src/domains/cluster_actors/consensus/voting.rs
src/domains/cluster_actors/heartbeats/heartbeat.rs
src/domains/cluster_actors/replication.rs
src/domains/query_parsers/query_io.rs
src/presentation/clients/controllers/handler.rs
src/presentation/clusters/listeners/peer_input.rs
src/services/handlers/cluster.rs

feat: prev_log_index and term taken into consideration on replication

---

src/adapters/wal/local_wal.rs
src/adapters/wal/memory_wal.rs
src/domains/append_only_files/interfaces.rs
src/domains/append_only_files/logger.rs
src/domains/cluster_actors/actor.rs
src/services/handlers/cluster.rs

Required log operation added
- log_start_index 
- truncate_after
- is_empty
`replicate` operation further encapsulated
`check_previous_entry_consistency` further articulated so it can capture edge cases
test added 
resolved #360

feat: Append entries RPC ravamped

---

src/domains/cluster_actors/actor.rs
src/domains/cluster_actors/commands/write_con.rs
src/domains/cluster_actors/mod.rs
src/domains/peers/peer.rs
src/domains/query_parsers/query_io.rs
src/presentation/clusters/inbound/stream.rs
src/presentation/clusters/listeners/mod.rs
src/presentation/clusters/outbound/stream.rs
src/services/handlers/cluster.rs

feat: decrease match index on log inconsistency detection

---

src/domains/cluster_actors/actor.rs
src/init.rs
src/lib.rs
src/services/handlers/cluster.rs
tests/common.rs

feat: paramerize topology path

---

src/domains/cluster_actors/actor.rs
src/domains/cluster_actors/commands/write_con.rs
src/domains/cluster_actors/consensus/mod.rs
src/domains/cluster_actors/consensus/voting.rs

feat: voter votes only once

---

src/presentation/clusters/inbound/stream.rs
tests/test_sync.rs

This pull request includes the following changes:
- **Fix**: Implemented a check for the peer kind to ensure proper handling of different peer types.
- **Test**: Added a test case for verifying the full synchronization process on a newly added replica. 
resolves: #380

fix: test_full_sync_on_newly_added_replica

---

src/domains/append_only_files/log.rs
src/domains/append_only_files/mod.rs
src/domains/cluster_actors/actor.rs
src/domains/cluster_actors/commands/election.rs
src/domains/cluster_actors/commands/mod.rs
src/domains/cluster_actors/commands/write_con.rs
src/domains/cluster_actors/consensus/log.rs
src/domains/cluster_actors/heartbeats/heartbeat.rs
src/domains/cluster_actors/mod.rs
src/domains/cluster_actors/replication.rs
src/domains/cluster_actors/session.rs
src/domains/peers/identifier.rs
src/presentation/clients/controllers/acceptor.rs
src/presentation/clients/controllers/handler.rs
src/presentation/clients/mod.rs
src/presentation/clients/request.rs
src/presentation/clients/stream.rs
src/presentation/clusters/communication_manager.rs
src/presentation/clusters/connection_manager.rs
src/services/handlers/cluster.rs

feat: client sessions integration & tests

---

duva/src/domains/cluster_actors/actor.rs
duva/src/services/handlers/cluster.rs
duva/tests/test_cluster_forget_makes_all_nodes_forget_target_node.rs
duva/tests/test_cluster_forget_when_wrong_id_given.rs
duva/tests/test_cluster_known_nodes_increase_when_new_replica_is_added.rs
duva/tests/test_leader_election.rs
duva/tests/test_removes_node_when_heartbeat_is_not_received_for_certain_time.rs

resolved #428 
Integration tests added to prevent this from happening again (`test_leader_election_twice`)

fix: reelection error

---

duva-cli/src/command.rs
duva-cli/src/controller.rs
duva/src/adapters/wal/local_wal.rs
duva/src/domains/append_only_files/log.rs
duva/src/domains/caches/actor.rs
duva/src/domains/caches/cache_manager.rs
duva/src/domains/caches/command.rs
duva/src/domains/saves/endec/mod.rs
duva/src/presentation/clients/controllers/handler.rs
duva/src/presentation/clients/parser.rs
duva/src/presentation/clients/request.rs
duva/src/services/handlers/cache.rs
duva/tests/test_del.rs

feat: delete operation

---

duva/src/domains/cluster_actors/heartbeats/scheduler.rs
duva/tests/common.rs
duva/tests/replication_ops/test_leader_election.rs

fix: electiont test

---

duva-client/src/command.rs
duva-client/src/controller.rs
duva/src/domains/cluster_actors/commands/mod.rs
duva/src/domains/cluster_actors/replication.rs
duva/src/presentation/clients/controllers/handler.rs
duva/src/presentation/clients/parser.rs
duva/src/presentation/clients/request.rs
duva/src/presentation/clusters/communication_manager.rs
duva/src/presentation/clusters/connection_manager.rs
duva/src/services/handlers/cluster.rs

feat: role command

---

duva-client/src/cli/editor.rs

commands like `exists` and `del` requires repeated suggestion on key.

feat: repeated pattern suggestion

---

duva-client/src/broker/mod.rs
duva-client/src/cli/editor/completion.rs
duva-client/src/cli/editor/hints.rs
duva-client/src/cli/main.rs
duva-client/src/command.rs
duva-client/src/controller.rs
duva/src/clients/mod.rs
duva/src/domains/caches/actor.rs
duva/src/domains/caches/cache_manager.rs
duva/src/domains/caches/cache_objects.rs
duva/src/domains/caches/command.rs
duva/src/domains/caches/read_queue.rs
duva/src/domains/query_parsers/query_io.rs
duva/src/presentation/clients/controller.rs
duva/src/presentation/clients/parser.rs
duva/src/presentation/clients/request.rs
duva/src/presentation/clients/stream.rs
duva/src/services/handlers/cache.rs
duva/tests/client_ops/mod.rs
duva/tests/client_ops/test_incr.rs
duva/tests/common.rs

feat: INCR

---

docs/_commands/echo.md
docs/_commands/ping.md
docs/_commands/replicaof.md

docs: commnads

---

duva-client/src/cli/editor/completion.rs
duva-client/src/cli/editor/hints.rs
duva-client/src/command.rs
duva-client/src/controller.rs
duva-client/src/lib.rs
duva/src/domains/error.rs
duva/src/presentation/clients/controller.rs
duva/src/presentation/clients/parser.rs
duva/src/presentation/clients/request.rs
duva/tests/client_ops/mod.rs
duva/tests/client_ops/test_decr.rs

resolved #440 
- Integration test added
- `incremental_change` method added to client action 
- `Decr` case handled together with `Incr` on matching

feat: DECR 

---

docs/_posts/2025-04-22-reconnection-on-reboot.md

docs: post on reconnection on reboot

---

duva/src/domains/cluster_actors/actor.rs
duva/src/init.rs
duva/src/lib.rs
duva/src/main.rs
duva/src/services/handlers/cluster.rs

feat: topology_file_handler

---

duva/src/domains/cluster_actors/actor.rs
duva/src/domains/peers/cluster_peer.rs
duva/src/services/handlers/cluster.rs

feat: gossip-based reconnection

---

Cargo.lock
duva/Cargo.toml
duva/src/adapters/op_logs/disk_based.rs
duva/src/adapters/op_logs/memory_based.rs
duva/src/domains/cluster_actors/actor.rs
duva/src/domains/cluster_actors/peer_connections/inbound/stream.rs
duva/src/domains/operation_logs/interfaces.rs
duva/src/domains/operation_logs/logger.rs
duva/src/main.rs
duva/src/services/handlers/cluster.rs

feat: disk-based operation logs

---

duva/src/adapters/op_logs/disk_based.rs
duva/src/domains/caches/actor.rs
duva/src/domains/cluster_actors/actor.rs
duva/src/domains/cluster_actors/mod.rs
duva/src/domains/cluster_actors/peer_connections/inbound/stream.rs
duva/src/domains/peers/cluster_peer.rs
duva/src/domains/peers/connected_peer_info.rs
duva/src/domains/peers/peer.rs
duva/src/domains/query_parsers/query_io.rs

this will mitigate the confusion on what types should be used and help decide on type of peer

refactor: peer state as struct

---

duva/src/domains/cluster_actors/actor.rs
duva/src/domains/peers/peer.rs

To add more data to cluster node metadata

feat: stuff match index data

---

docs/_posts/2025-04-30-deferred_validation.markdown
duva-client/src/broker/mod.rs
duva/src/adapters/op_logs/disk_based.rs
duva/src/adapters/op_logs/memory_based.rs
duva/src/domains/caches/cache_manager.rs
duva/src/domains/caches/cache_objects.rs
duva/src/domains/cluster_actors/actor.rs
duva/src/domains/operation_logs/operation.rs
duva/src/domains/peers/peer.rs
duva/src/domains/query_parsers/query_io.rs
duva/src/presentation/clients/controller.rs
duva/src/presentation/clients/request.rs
duva/src/services/handlers/cluster.rs

Operations affected are:
- `INCR`
- `INCRBY`
- `DECR`
- `DECRBY`
- `APPEND`
Resolved #521

feat: post logging validation on delta changes

---

duva/src/domains/caches/actor.rs
duva/src/domains/cluster_actors/hash_ring.rs

feat: get token ranges / take subset

---

duva-client/src/cli/editor/completion.rs
duva-client/src/cli/editor/hints.rs
duva-client/src/controller.rs
duva/src/presentation/clients/controller.rs
duva/src/presentation/clients/request.rs

feat: cli - cluster meet

---

diagrams/consistent-hashing-server.mmd
duva/src/domains/cluster_actors/actor.rs
duva/src/domains/cluster_actors/commands/cluster_actor_command.rs
duva/src/domains/cluster_actors/commands/mod.rs
duva/src/presentation/clients/controller.rs
duva/src/services/handlers/cluster.rs

feat: delaying client requests 

---

README.md
diagrams/partial_sync.mmd
duva/src/domains/caches/cache_manager.rs
duva/src/domains/cluster_actors/actor.rs
duva/src/domains/operation_logs/interfaces.rs
duva/src/domains/operation_logs/logger.rs
duva/src/domains/operation_logs/operation.rs
duva/src/presentation/clients/request.rs
duva/src/services/handlers/cluster.rs
duva/tests/cluster_ops/test_reconnection_on_reboot.rs

feat:  partial sync and log reconcilation

---

Cargo.lock
duva/Cargo.toml
duva/src/domains/caches/cache_manager.rs
duva/src/domains/cluster_actors/actor.rs
duva/src/domains/cluster_actors/heartbeats/scheduler.rs
duva/src/domains/cluster_actors/listener.rs
duva/src/domains/config_actors/config_manager.rs
duva/src/domains/operation_logs/logger.rs
duva/src/lib.rs
duva/src/main.rs
duva/src/presentation/clients/controller.rs
duva/src/presentation/clients/stream.rs
duva/src/presentation/clusters/communication_manager.rs
duva/tests/client_ops/test_keys.rs
duva/tests/common.rs
duva/tests/replication_ops/test_raft_happy_case.rs

logging support based on span and context

feat: tracing on client requests 

---

duva-client/src/cli/editor/completion.rs
duva-client/src/cli/editor/hints.rs
duva/src/domains/cluster_actors/actor.rs
duva/src/domains/cluster_actors/commands/cluster_actor_command.rs
duva/src/domains/cluster_actors/replication.rs
duva/src/macros.rs
duva/src/presentation/clients/controller.rs
duva/src/presentation/clients/stream.rs
duva/src/presentation/clusters/communication_manager.rs
duva/src/services/handlers/cluster.rs
duva/tests/cluster_ops/test_lazy_discovery.rs

feat: block invalid operation on self

---

Makefile
diagrams/clustering.mmd
diagrams/consistent-hashing-server.mmd
duva-client/src/controller.rs
duva/src/domains/cluster_actors/actor.rs
duva/src/domains/cluster_actors/commands/cluster_actor_command.rs
duva/src/domains/cluster_actors/peer_connections/outbound/stream.rs
duva/src/domains/operation_logs/logger.rs
duva/src/domains/query_parsers/query_io.rs
duva/src/lib.rs
duva/src/presentation/clients/controller.rs
duva/src/presentation/clusters/communication_manager.rs
duva/src/services/handlers/cluster.rs
duva/tests/cluster_ops/mod.rs
duva/tests/cluster_ops/test_cluster_meet.rs
duva/tests/common.rs

feat: cluster meet outline

---

duva/src/domains/cluster_actors/hash_ring.rs

To successfully replicate hash ring information across cluster, last_modified value is required so node can decide
what to add. 
#530

feat: last modified added to hash ring

---

duva/src/domains/caches/actor.rs
duva/src/domains/caches/cache_db.rs
duva/src/domains/caches/cache_db/cache_node.rs
duva/src/domains/caches/cache_db/entry.rs
duva/src/domains/caches/cache_db/iter.rs
duva/src/domains/caches/cache_db/tests.rs
duva/src/domains/caches/mod.rs
duva/src/domains/caches/service.rs

Implement LRU implements for cache db

---

diagrams/consistent-hashing-server.mmd
duva/src/domains/cluster_actors/actor.rs
duva/src/domains/cluster_actors/actor/tests/mod.rs
duva/src/domains/cluster_actors/actor/tests/partitionings.rs
duva/src/domains/cluster_actors/command.rs
duva/src/domains/cluster_actors/hash_ring/migration_task.rs
duva/src/domains/cluster_actors/service.rs
duva/src/domains/peers/connections/inbound/stream.rs
duva/tests/replication_ops/test_leader_election.rs

feat: bulk delete consensus, lazy unblocking, state reflection

---

duva/src/domains/caches/cache_manager.rs
duva/src/domains/cluster_actors/actor.rs
duva/src/domains/cluster_actors/actor/tests/mod.rs
duva/src/domains/cluster_actors/actor/tests/partitionings.rs
duva/src/domains/cluster_actors/command.rs
duva/src/domains/cluster_actors/service.rs
duva/src/domains/operation_logs/operation.rs
duva/src/domains/peers/command.rs

feat: set consensus on rebalancing

---

duva/src/domains/cluster_actors/actor/tests/replications.rs
duva/src/domains/cluster_actors/consensus/log.rs

fix: client hang after election

---

duva/src/domains/cluster_actors/actor.rs
duva/src/domains/cluster_actors/actor/tests/replications.rs
duva/src/domains/cluster_actors/command.rs
duva/src/domains/cluster_actors/service.rs
duva/tests/cluster_ops/test_cluster_forget_when_wrong_id_given.rs

- encapsulation
- improve testability

refactor: leader requests consensus

---

duva/src/domains/cluster_actors/actor.rs
duva/src/domains/cluster_actors/actor/tests/cluster_managements.rs
duva/src/domains/cluster_actors/actor/tests/elections.rs
duva/src/domains/cluster_actors/actor/tests/mod.rs
duva/src/domains/cluster_actors/replication.rs
duva/src/domains/peers/connections/connection_types.rs
duva/src/domains/peers/connections/inbound/request.rs
duva/src/domains/peers/connections/inbound/stream.rs
duva/src/domains/peers/connections/outbound/stream.rs
duva/src/domains/peers/peer.rs
duva/src/domains/query_io.rs
duva/src/presentation/clients/controller.rs
duva/tests/common.rs
duva/tests/replication_ops/test_leader_election.rs

feat: leadership information propagation through gossip

---

duva/src/domains/cluster_actors/actor.rs
duva/src/domains/cluster_actors/actor/tests/cluster_managements.rs
duva/src/domains/cluster_actors/actor/tests/elections.rs
duva/src/domains/cluster_actors/actor/tests/mod.rs
duva/src/domains/cluster_actors/actor/tests/partitionings.rs
duva/src/domains/cluster_actors/replication.rs
duva/src/domains/peers/connections/connection_types.rs
duva/src/domains/peers/peer.rs
duva/src/domains/query_io.rs
duva/src/lib.rs
duva/tests/cluster_ops/test_lazy_discovery.rs
duva/tests/common.rs

feat: kill node kind

---

duva/src/domains/cluster_actors/service.rs
duva/src/presentation/clients/request.rs
duva/tests/replication_ops/test_leader_election.rs

feat: reshard

---

duva/src/domains/cluster_actors/actor.rs
duva/src/domains/cluster_actors/actor/tests/cluster_managements.rs
duva/src/domains/cluster_actors/actor/tests/partitionings.rs
duva/src/domains/cluster_actors/hash_ring.rs
duva/src/domains/cluster_actors/hash_ring/tests/add_and_remove.rs
duva/src/domains/cluster_actors/hash_ring/tests/migration.rs
duva/src/domains/query_io.rs

feat: hashring based on current shard leaders

---

diagrams/consistent-hashing-server.mmd
duva-client/src/broker/mod.rs
duva/src/domains/cluster_actors/actor.rs
duva/src/domains/cluster_actors/actor/tests/partitionings.rs

fix: apply optimistic migration, resolve hashring update timing issue

---

duva/src/domains/cluster_actors/actor.rs
duva/src/domains/cluster_actors/actor/tests/elections.rs
duva/src/domains/cluster_actors/actor/tests/partitionings.rs
duva/src/domains/cluster_actors/service.rs
duva/src/macros.rs

refactor: error, file logging

---

duva/src/adapters/op_logs/disk_based.rs
duva/src/domains/cluster_actors/hash_ring.rs
duva/tests/replication_ops/test_leader_election.rs

from time based assumptions to retry count based one

fix : test on leader election

---

duva-client/Cargo.toml
duva/Cargo.toml

enhancement: optimize LTO

---

duva-client/src/controller.rs
duva/src/domains/caches/actor.rs
duva/src/domains/caches/cache_manager.rs
duva/src/domains/caches/cache_objects/value.rs
duva/src/domains/caches/command.rs
duva/src/domains/caches/read_queue.rs
duva/src/domains/caches/service.rs
duva/src/domains/cluster_actors/actor.rs
duva/src/domains/cluster_actors/actor/tests/partitionings.rs
duva/src/domains/query_io.rs
duva/src/domains/saves/endec/encoder.rs
duva/src/presentation/clients/controller.rs

feat: List type support on server side

---

duva/src/config.rs
duva/src/domains/peers/connections/outbound/stream.rs
duva/src/domains/peers/identifier.rs
duva/src/domains/peers/peer.rs
duva/src/domains/query_io.rs
duva/src/presentation/clients/controller.rs
duva/src/presentation/clients/request.rs
duva/src/presentation/clusters/communication_manager.rs

fix: server panic when wrong connection is attempted

---

duva-client/src/controller.rs
duva/src/domains/caches/actor.rs
duva/src/domains/caches/cache_manager.rs
duva/src/domains/caches/command.rs
duva/src/domains/caches/service.rs
duva/src/domains/operation_logs/operation.rs
duva/src/presentation/clients/controller.rs
duva/src/presentation/clients/request.rs
duva/tests/client_ops/mod.rs
duva/tests/client_ops/test_rpush.rs
duva/tests/common.rs

Adds the RPUSH command, which is a write operation. The changes also include refactoring to extract the action and a fix for a wrong package reference.

feat: RPUSH 

---

duva-client/src/controller.rs
duva/src/domains/caches/actor.rs
duva/src/domains/caches/cache_manager.rs
duva/src/domains/caches/command.rs
duva/src/domains/caches/service.rs
duva/src/presentation/clients/controller.rs
duva/src/presentation/clients/request.rs
duva/tests/client_ops/mod.rs
duva/tests/client_ops/test_llen.rs

feat: llen

---

duva-client/src/controller.rs
duva/src/domains/caches/actor.rs
duva/src/domains/caches/cache_manager.rs
duva/src/domains/caches/command.rs
duva/src/domains/caches/lru_cache.rs
duva/src/domains/caches/service.rs
duva/src/presentation/clients/controller.rs
duva/src/presentation/clients/request.rs
duva/tests/client_ops/mod.rs
duva/tests/client_ops/test_llen.rs
duva/tests/client_ops/test_lrange.rs

feat LRange

---

duva-client/src/controller.rs
duva/src/domains/caches/actor.rs
duva/src/domains/caches/cache_manager.rs
duva/src/domains/caches/cache_objects/types/quicklist.rs
duva/src/domains/caches/command.rs
duva/src/domains/caches/service.rs
duva/src/domains/operation_logs/operation.rs
duva/src/presentation/clients/controller.rs
duva/src/presentation/clients/request.rs
duva/tests/client_ops/mod.rs
duva/tests/client_ops/test_lset.rs

feat: lset

---

duva/src/domains/cluster_actors/actor.rs

preliminary step to fix the issue #768

feat: lift up connection restriction

---

duva/src/domains/cluster_actors/actor.rs
duva/src/domains/peers/connections/outbound/stream.rs

feat: creation delegated to connect_to_server for outbound stream

---

duva-client/src/broker/read_stream.rs
duva/src/adapters/io/tokio_stream.rs
duva/src/domains/caches/actor.rs
duva/src/domains/caches/cache_manager.rs
duva/src/domains/caches/command.rs
duva/src/domains/caches/read_queue.rs
duva/src/domains/caches/service.rs
duva/src/domains/cluster_actors/actor.rs
duva/src/domains/cluster_actors/actor/heartbeat_scheduler.rs
duva/src/domains/cluster_actors/actor/tests/cluster_managements.rs
duva/src/domains/cluster_actors/actor/tests/mod.rs
duva/src/domains/cluster_actors/actor/tests/partitionings.rs
duva/src/domains/cluster_actors/actor/tests/replications.rs
duva/src/domains/cluster_actors/command.rs
duva/src/domains/cluster_actors/consensus/log.rs
duva/src/domains/cluster_actors/service.rs
duva/src/domains/interface.rs
duva/src/domains/peers/peer.rs
duva/src/domains/peers/service.rs
duva/src/presentation/clients/controller.rs
duva/src/presentation/clusters/communication_manager.rs
duva/src/types.rs

chore: connector read write / callback wrapper

---

README.md
diagrams/follower_reads.mmd
diagrams/full_sync_scenario_snapshot.mmd
diagrams/full_sync_scenario_with_append_entry.mmd
diagrams/full_sync_when_commit_was_made.mmd
diagrams/raft(5) - commit based on hwm.mmd
diagrams/raft(6) - discard based on hwm.mmd
duva-client/src/command.rs
duva/src/domains/caches/actor.rs
duva/src/domains/caches/cache_manager.rs
duva/src/domains/caches/read_queue.rs
duva/src/domains/caches/service.rs
duva/src/domains/cluster_actors/actor.rs
duva/src/domains/cluster_actors/actor/tests/cluster_managements.rs
duva/src/domains/cluster_actors/actor/tests/mod.rs
duva/src/domains/cluster_actors/actor/tests/partitionings.rs
duva/src/domains/cluster_actors/actor/tests/replications.rs
duva/src/domains/cluster_actors/replication.rs
duva/src/domains/operation_logs/logger.rs
duva/src/domains/peers/command.rs
duva/src/domains/peers/connections/connection_types.rs
duva/src/domains/peers/connections/inbound/stream.rs
duva/src/domains/peers/connections/outbound/stream.rs
duva/src/domains/peers/peer.rs
duva/src/domains/query_io.rs
duva/src/lib.rs
duva/src/presentation/clients/controller.rs

to reduce confusion, rename hwm to consensus_index

chore: rename hwm to consensus index

---

duva/src/presentation/clients/controller.rs
duva/src/presentation/clients/request.rs
duva/src/presentation/clients/stream.rs

feat: read/write separation
