- src/lib.rs
- src/main.rs
- tests/common.rs
- tests/test_config_get_dir.rs
- tests/test_keys.rs
- tests/test_replication_info.rs
- tests/test_set_get.rs
`TNotifyStartupWaiter` is defined to signal each binary that server is up and running.
This is to reduce warm up delay
> test: notify start up waiter

- src/adapters/cancellation_token.rs
- src/adapters/mod.rs
- src/lib.rs
- src/main.rs
- src/services/query_manager/interface.rs
- src/services/query_manager/mod.rs
- tests/common.rs
- tests/test_cancellation_token.rs
- tests/test_config_get_dir.rs
- tests/test_keys.rs
- tests/test_replication_info.rs
- tests/test_set_get.rs
Cancellation token implemented.
Exactly when and how it will be used will be decided later. 
traits defined within `query_manager` may be relocated to service interface if it becomes cross-functional concern.
> feat: cancellation token 

- src/lib.rs
- src/main.rs
- src/services/config/config_actor.rs
- tests/common.rs
There is increasing need for passing dependencies, each of which can be entire subsystem, to `start_up` function. 
And then it manages lifecycles, bootstrapping and the like. 
Before it gets bigger and bigger, I figured structural design should be introduced.
> refactor: startup facade

- src/adapters/io/tokio_stream.rs
- src/lib.rs
- src/main.rs
- src/services/cluster/actor.rs
- src/services/cluster/mod.rs
- src/services/config/command.rs
- src/services/config/config_actor.rs
- src/services/config/config_manager.rs
- src/services/mod.rs
- src/services/stream_manager/interface.rs
- src/services/stream_manager/mod.rs
- src/services/stream_manager/replication_request_controllers/mod.rs
- tests/common.rs
- tests/test_cancellation_token.rs
- tests/test_config_get_dir.rs
- tests/test_disseminate_peers.rs
- tests/test_handshake.rs
- tests/test_heartbeat.rs
- tests/test_heartbeat_broadcasting.rs
- tests/test_keys.rs
- tests/test_replication_info.rs
- tests/test_save_read_dump.rs
- tests/test_set_get.rs
#112 
#116 
#114 
Reason for the change:
The system has a significant dependency on the Tokio runtime, which I initially considered a volatile and potentially risky dependency. However, this dependency cascades throughout the codebase—from main to startup and down to each dispatcher—introducing unnecessary generic complexity.
Additionally, as the `ClusteringManager` is expected to manage streams, this generic coupling hinders the domain from remaining implementation-specific.
I could've just used dynamic dispatch but it's only adding up the cost - which we shouldn't without valid reasons.
> feat: cluster manager outlined

- src/adapters/io/tokio_stream.rs
- src/lib.rs
- src/services/cluster/actor.rs
- src/services/cluster/manager.rs
- src/services/config/manager.rs
- src/services/stream_manager/interface.rs
- tests/common.rs
- tests/test_disseminate_peers.rs
- tests/test_heartbeat.rs
- tests/test_heartbeat_broadcasting.rs
Client used in test was implemented with the wrong assumption that client port can be static - which is simply wrong. 
Everytime client makes connection, dynamic port is allocated . 
Identifying client based on its IP and port is not, therefore, a viable option.
> fix: client port assumption

- src/lib.rs
- src/services/config/manager.rs
- src/services/stream_manager/request_controller/client/mod.rs
instead of returning `oneshot::Receiver<_>`, it extract the response and return.
> refactor: simplify route query

- src/lib.rs
- src/services/config/manager.rs
- src/services/stream_manager/request_controller/client/mod.rs
failover is implemented using atomic boolean that denotes the mode and `watch` channel and multiplexing. 
Now, slave can safely take over master role when the flag is on. 
#131
> feat: dynamic role change on mode change

- src/lib.rs
- src/services/client/manager.rs
- src/services/client/mod.rs
- src/services/cluster/actor.rs
- src/services/cluster/actors/actor.rs
- src/services/cluster/actors/command.rs
- src/services/cluster/actors/listening_actor.rs
- src/services/cluster/actors/mod.rs
- src/services/cluster/inbound/mod.rs
- src/services/cluster/inbound/request.rs
- src/services/cluster/inbound/stream.rs
- src/services/cluster/manager.rs
- src/services/cluster/mod.rs
- src/services/cluster/outbound/mod.rs
- tests/common.rs
`PeerListeningActor` is responsible for listening to incoming messages from a peer.
Message from a peer is one of events that can trigger a change in the cluster state.
As the system has to keep listening to incoming messages, it is implemented as an actor, run in the background.
To take a control of the actor, PeerListenerHandler is used, which can kill the listening process and return the connected stream.
closes #132
> feat: cluster listening actor

- src/services/cluster/actors/actor.rs
- src/services/cluster/actors/command.rs
- src/services/cluster/actors/listening_actor.rs
- src/services/cluster/actors/mod.rs
- src/services/cluster/actors/types.rs
- src/services/cluster/inbound/stream.rs
- src/services/cluster/manager.rs
- tests/common.rs
- tests/test_disseminate_peers.rs
- tests/test_handshake.rs
- tests/test_heartbeat.rs
- tests/test_heartbeat_broadcasting.rs
- Testcode refactored into process-based one
- PORT_DISTRIBUTER used for simplicity
- Listener specific command implemented
- Heartbeat tested
> feat: master heartbeat implementation

- src/lib.rs
- src/main.rs
- src/services/client/manager.rs
- src/services/cluster/actors/actor.rs
- src/services/cluster/actors/command.rs
- src/services/cluster/actors/mod.rs
- src/services/cluster/actors/replication.rs
- src/services/cluster/manager.rs
- src/services/cluster/mod.rs
- src/services/config/actor.rs
- src/services/config/command.rs
- src/services/config/init.rs
- src/services/config/manager.rs
- src/services/config/mod.rs
- tests/common.rs
- tests/test_cancellation_token.rs
- tests/test_heartbeat_broadcasting.rs
Currently, replication information was implemented under config which makes it difficult to draw the line between cluster actor and config actor. 
It gets worse when we implement leader election for example which inherently changes replication information.
In this PR, the following was implemented
- environment variable collector -which will be used once when we construct startup facade
- moving replication under cluster actor
- relavant refactoring
> refactor: move replication in preparation for leader election

- src/services/cluster/actors/actor.rs
- src/services/cluster/actors/command.rs
- src/services/cluster/actors/mod.rs
- src/services/cluster/actors/peer.rs
- src/services/cluster/actors/replication.rs
- src/services/cluster/manager.rs
- src/services/cluster/outbound/response.rs
- src/services/cluster/outbound/stream.rs
- src/services/config/manager.rs
- src/services/query_io.rs
To share `PeerState`, it has to have sequence info and master repl id so when it reaches peers their identity can be  found.
> feat: state on replication 

- src/services/cluster/actors/actor.rs
- src/services/cluster/actors/command.rs
- src/services/cluster/actors/listening_actor.rs
- tests/common.rs
- tests/test_heartbeat.rs
hop_count decreasing logic implemented. 
Use of existing `ReportAlive` command variant, after update operation is done which is non fallible, try gossip if there is remaining hop count. 
resolves #192 
resolves #189
> feat: gossip method using `ReportAlive` command variant

- src/services/cluster/actors/actor.rs
- src/services/cluster/replications/replication.rs
while propagating ban_list, each node shoud:
1) register banned peer on the list
2) check on its ban_time - which doesn't require strong accuracy
3) remove the peer from its peer list
4) gossip that information 
This PR is for 3. and rest of them were done previously.
> feat: remove nodes based on ban list

- Cargo.lock
- Cargo.toml
- src/services/cluster/actors/actor.rs
- src/services/cluster/replications/replication.rs
Original:
```rust
for peer in self.replicas() {
let _ = peer.write_io(heartbeat.clone()).await;
}
```
This sequential execution will be normalized as system starts getting more and more traffics.
I figured latency of N × (avg. latency of write_io) is not acceptable where N is the number of replicas for consensus job.
I considered the following:
```rust
join_all(self.replicas().into_iter().map(|peer| peer.write_io(heartbeat.clone()))).await;
```
this is fast enough but as it takes order into consideration, it's slightly slower. 
There comes the current implementation:
```rust
let mut tasks = self
.replicas()
.into_iter()
.map(|peer| peer.write_io(heartbeat.clone()))
.collect::<FuturesUnordered<_>>();
while let Some(_) = tasks.next().await {}
```
Obviously, we don't care about the order. …
> feat: fully concurrent, unordered execution

- tests/test_cluster_forget_node_propagation.rs
- tests/test_cluster_forget_when_wrong_id_given.rs
This PR aimed at mitigating the chances of port collision. 
Judging by how tests are run in integration tests, it seems tests in the same module runs together. 
If that's the case, it's highly likely that they causes port collision, leading to flakiness.
> test: separate tests to prevent port collision

- src/domains/saves/actor.rs
- src/domains/saves/endec/decoder/byte_decoder.rs
- src/domains/saves/endec/decoder/states.rs
- src/domains/saves/endec/encoder/byte_encoder.rs
- src/domains/saves/endec/mod.rs
- src/domains/saves/snapshot/snapshot.rs
- src/lib.rs
**Changes Made:**
- Now Header Name is `DUVA` and Version Name is `0001`
- Updated the implementation to enforce the requirement for `repl_id` and `repl_offset`, ensuring they are mandatory fields.
> enhancement: repl_id,repl_offset non optional

- tests/common.rs
- tests/test_replication_info.rs
Current Global value distribution didn't work as integration tests run sequentially unless there are not in the same module.
Instead of handling this, this PR fixed the code so OS can dynamically allocate the port.
> test-fix: port collision 

- diagrams/raft(6) - discard based on hwm copy.mmd
- diagrams/raft(7) - idempotent receiver.mmd
In case leader failure, client would retry the same request. 
That can lead to the problem ; we don't want to make the same transfer twice. 
Idempotency can be achieved by:
- registering client with the leader before sending any requests
- replication of registration
- asking for `client id` submission and unique `request id` 
This PR draws how it works in sequence diagram.
> doc: idempotent receiver

- src/domains/cluster_actors/actor.rs
- src/domains/cluster_actors/replication.rs
- src/domains/peers/connected_peer_info.rs
- src/domains/peers/kind.rs
- src/domains/peers/mod.rs
- src/domains/peers/peer.rs
- src/lib.rs
- src/presentation/cluster_in/connection_manager.rs
- src/presentation/cluster_in/inbound/stream.rs
- src/presentation/cluster_in/outbound/response.rs
- src/presentation/cluster_in/outbound/stream.rs
there must be distinction between peer follower and peer leader so the system can communicate cluster node information.
#298
> feat: peer follower & peer leader

- Makefile
- src/domains/peers/peer.rs
- src/init.rs
- src/presentation/clusters/connection_manager.rs
- tests/common.rs
- tests/test_cluster_known_nodes_increase_when_new_replica_is_added.rs
This pull request includes the following changes:
- Added a Makefile for build automation.
- Fixed the issue of replacing peers' replid during the first connection.
- Added tests for topology changes.
> fix: replace new follower's repl id from leader side

- duva/tests/test_leader_election.rs
closed #430 
There was a bug where after election, write operation after the first one failed. 
Although bug was fixed with the previous [PR](https://github.com/Migorithm/duva/pull/430)
There is no test for this; therefore this PR.
> test: set twice after election

- duva-client/src/cli/main.rs
- duva-client/src/command.rs
- duva-client/src/controller.rs
- duva/src/clients/authentications.rs
- duva/src/clients/utils.rs
- duva/src/domains/peers/identifier.rs
- duva/src/domains/peers/mod.rs
- duva/src/lib.rs
- duva/src/presentation/clients/stream.rs
basic implementation for  #427 
backlogs : reseeding cluster nodes on add_peer from leader to all the connected clients
> feat: pull-based reconnection to new leader instance

- duva/src/adapters/wal/local_wal.rs
- duva/src/domains/append_only_files/log.rs
- duva/src/domains/cluster_actors/actor.rs
- duva/src/domains/peers/peer.rs
> chore: cleanup

- duva/src/domains/caches/command.rs
- duva/src/domains/cluster_actors/actor.rs
- duva/src/services/handlers/cluster.rs
- duva/tests/cluster_ops/test_cluster_forget_makes_all_nodes_forget_target_node.rs
unique combination of
- multi-threaded test
- timing assumptions
- eventual consistency 
makes the test flaky. This PR is aimed at achieving determinism on the test
> fix: flaky test

- duva/src/adapters/op_logs/disk_based.rs
- duva/src/domains/cluster_actors/commands/peer_listener_command.rs
- duva/src/domains/operation_logs/operation.rs
- duva/src/domains/query_parsers/query_io.rs
- remove useless bytesmut for reducing useless permission
- turn slice method from raw slicing
> Using bytes crate efficiently

- duva/tests/common.rs
Prevent timeout on spawn_server_process by increasing it, due to slow github action hosted CI environments.
> Increase spawn_server_process timeout

- duva/tests/client_ops/test_config_get_dir.rs
- duva/tests/client_ops/test_decr.rs
- duva/tests/client_ops/test_del.rs
- duva/tests/client_ops/test_exists.rs
- duva/tests/client_ops/test_incr.rs
- duva/tests/client_ops/test_keys.rs
- duva/tests/client_ops/test_replication_info.rs
- duva/tests/client_ops/test_set_get.rs
- duva/tests/client_ops/test_snapshot_persists_and_recovers_state.rs
- duva/tests/client_ops/test_ttl.rs
- duva/tests/cluster_ops/test_cluster_forget_makes_all_nodes_forget_target_node.rs
- duva/tests/cluster_ops/test_cluster_forget_when_wrong_id_given.rs
- duva/tests/cluster_ops/test_cluster_known_nodes_increase_when_new_replica_is_added.rs
- duva/tests/cluster_ops/test_heartbeat.rs
- duva/tests/cluster_ops/test_lazy_discovery.rs
- duva/tests/cluster_ops/test_reconnection_on_reboot.rs
- duva/tests/cluster_ops/test_removes_node_when_heartbeat_is_not_received_for_certain_time.rs
- duva/tests/common.rs
- duva/tests/replication_ops/test_leader_election.rs
- duva/tests/replication_ops/test_raft_happy_case.rs
- duva/tests/replication_ops/test_sync.rs
This PR implements below:
- Fully integration with `tokio::process::{Child, Command}` and async tests
> Integraton with tokio process, child instead of std

- diagrams/consistent_hashing.mmd
Simplified view on how consistent hashing works. 
Replicas and partitions were not drawn for simplicity.
> doc: consistent hashing

- duva/src/adapters/op_logs/disk_based.rs
- duva/src/adapters/op_logs/memory_based.rs
- duva/src/domains/operation_logs/interfaces.rs
- duva/tests/client_ops/test_config_get_dir.rs
- duva/tests/client_ops/test_decr.rs
- duva/tests/client_ops/test_del.rs
- duva/tests/client_ops/test_exists.rs
- duva/tests/client_ops/test_incr.rs
- duva/tests/client_ops/test_keys.rs
- duva/tests/client_ops/test_replication_info.rs
- duva/tests/client_ops/test_set_get.rs
- duva/tests/client_ops/test_snapshot_persists_and_recovers_state.rs
- duva/tests/client_ops/test_ttl.rs
- duva/tests/cluster_ops/test_cluster_forget_makes_all_nodes_forget_target_node.rs
- duva/tests/cluster_ops/test_cluster_forget_when_wrong_id_given.rs
- duva/tests/cluster_ops/test_cluster_known_nodes_increase_when_new_replica_is_added.rs
- duva/tests/cluster_ops/test_heartbeat.rs
- duva/tests/cluster_ops/test_lazy_discovery.rs
- duva/tests/cluster_ops/test_reconnection_on_reboot.rs
- duva/tests/cluster_ops/test_removes_node_when_heartbeat_is_not_received_for_certain_time.rs
- duva/tests/common.rs
- duva/tests/replication_ops/test_leader_election.rs
- duva/tests/replication_ops/test_raft_happy_case.rs
- duva/tests/replication_ops/test_sync.rs
Updated out integrated tests to run with and without append only files. 
As a drive-by change, created a temporary directory for each ServerEnv, and passed that as the base dir to the application (topology file path is defined in this temporary directory with a random file name).
Resolved #511
> run integrated tests with and without disk-based append only files

- duva-client/src/broker/mod.rs
- duva-client/src/cli/main.rs
- duva-client/src/controller.rs
- duva/src/domains/cluster_actors/hash_ring.rs
- duva/tests/client_ops/test_append.rs
- duva/tests/client_ops/test_config_get_dir.rs
- duva/tests/client_ops/test_decr.rs
- duva/tests/client_ops/test_del.rs
- duva/tests/client_ops/test_exists.rs
- duva/tests/client_ops/test_incr.rs
- duva/tests/client_ops/test_keys.rs
- duva/tests/client_ops/test_replication_info.rs
- duva/tests/client_ops/test_set_get.rs
- duva/tests/client_ops/test_snapshot_persists_and_recovers_state.rs
- duva/tests/client_ops/test_ttl.rs
- duva/tests/cluster_ops/test_cluster_forget_makes_all_nodes_forget_target_node.rs
- duva/tests/cluster_ops/test_cluster_forget_when_wrong_id_given.rs
- duva/tests/cluster_ops/test_cluster_known_nodes_increase_when_new_replica_is_added.rs
- duva/tests/cluster_ops/test_heartbeat.rs
- duva/tests/cluster_ops/test_lazy_discovery.rs
- duva/tests/cluster_ops/test_reconnection_on_reboot.rs
- duva/tests/cluster_ops/test_removes_node_when_heartbeat_is_not_received_for_certain_time.rs
- duva/tests/common.rs
- duva/tests/replication_ops/test_leader_election.rs
- duva/tests/replication_ops/test_raft_happy_case.rs
- duva/tests/replication_ops/test_sync.rs
The changes made from this [PR](https://github.com/Migorithm/duva/pull/498) causes zombie processes springing up. 
Turns out, `terminate` wasn't triggered and in the review process it was overlooked / missed.
> bug: zombie process due to async-based test 

- Cargo.lock
- duva/Cargo.toml
- duva/src/presentation/clients/stream.rs
- duva/tests/client_ops/test_append.rs
- duva/tests/client_ops/test_config_get_dir.rs
- duva/tests/client_ops/test_decr.rs
- duva/tests/client_ops/test_decrby.rs
- duva/tests/client_ops/test_del.rs
- duva/tests/client_ops/test_exists.rs
- duva/tests/client_ops/test_incr.rs
- duva/tests/client_ops/test_incrby.rs
- duva/tests/client_ops/test_keys.rs
- duva/tests/client_ops/test_replication_info.rs
- duva/tests/client_ops/test_set_get.rs
- duva/tests/client_ops/test_snapshot_persists_and_recovers_state.rs
- duva/tests/client_ops/test_ttl.rs
- duva/tests/cluster_ops/test_cluster_forget_makes_all_nodes_forget_target_node.rs
- duva/tests/cluster_ops/test_cluster_forget_when_wrong_id_given.rs
- duva/tests/cluster_ops/test_cluster_known_nodes_increase_when_new_replica_is_added.rs
- duva/tests/cluster_ops/test_lazy_discovery.rs
- duva/tests/cluster_ops/test_reconnection_on_reboot.rs
- duva/tests/cluster_ops/test_removes_node_when_heartbeat_is_not_received_for_certain_time.rs
- duva/tests/common.rs
- duva/tests/replication_ops/test_leader_election.rs
- duva/tests/replication_ops/test_raft_happy_case.rs
- duva/tests/replication_ops/test_sync.rs
`set_and_get` has required cnt logic in case it requires more than a line.
For most of test case this is not needed. So one liner method that simply return `String` is added to simplify test.
> test: cnt not requiring helper method

- duva/src/domains/caches/actor.rs
- duva/src/domains/cluster_actors/actor.rs
- duva/src/domains/cluster_actors/commands/cluster_actor_command.rs
- duva/src/domains/cluster_actors/consensus/election.rs
- duva/src/domains/cluster_actors/listener.rs
- duva/src/domains/cluster_actors/peer_connections/inbound/stream.rs
- duva/src/domains/cluster_actors/peer_connections/outbound/stream.rs
- duva/src/domains/cluster_actors/replication.rs
- duva/src/domains/peers/connected_peer_info.rs
- duva/src/domains/peers/identifier.rs
- duva/src/lib.rs
- duva/src/presentation/clusters/communication_manager.rs
- duva/src/services/handlers/cluster.rs
- duva/tests/cluster_ops/test_cluster_meet.rs
- duva/tests/cluster_ops/test_heartbeat.rs
- duva/tests/common.rs
- duva/tests/replication_ops/test_leader_election.rs
As cluster actor is single synchronization point, hangs on cluster actor may incur logical deadlock. 
This PR is aimed at improving that process .
When synchrornization happens in cluster actor, concurrent handshakes requests can block each other, leading to operational deadlock.
classic issue in distributed systems when implementing a gossip protocol: concurrent connection attempts between two nodes (B and C) leading to duplicate connections, where only one should persist due to the constraint of maintaining a single stream.
> feat: background handshake spawn from inbound stream

- duva-client/src/cli/editor/hints.rs
- duva/src/domains/cluster_actors/actor.rs
- duva/src/domains/cluster_actors/commands/command.rs
- duva/src/domains/cluster_actors/commands/mod.rs
- duva/src/domains/cluster_actors/service.rs
- duva/src/presentation/clients/controller.rs
- duva/src/presentation/clients/request.rs
- duva/src/presentation/clusters/communication_manager.rs
`Cluster Meet` operation may/may not trigger rebalancing right on arrival of request. 
`LazyOption` will decide how promptly it will react. 
If `Eager` is given, it will ask connected node to start rebalancing, blocking subsequent user write opeartions.
Otherwise, it will wait until client triggers rebalancing. 
#530
> feat: optional rebalancing trigger

- duva/src/domains/cluster_actors/actor.rs
- duva/src/domains/cluster_actors/service.rs
- duva/src/domains/cluster_actors/session.rs
- duva/src/domains/operation_logs/logger.rs
- duva/src/lib.rs
quite a bit of lines depends on internally/externally logger. 
Having realized that ClusterActor is indeed synchronization point, it's natural to observe common usecase between cluster actor and  replicated logs. Therefore, this PR is aimed at having `ClusterActor` encapsulate `ReplicatedLogs`.
> refactor: encapsulate logger

- duva/src/domains/caches/actor.rs
- duva/src/domains/caches/cache_db.rs
- duva/src/domains/caches/cache_db/cache_node.rs
- duva/src/domains/caches/cache_manager.rs
- duva/src/domains/caches/command.rs
- duva/src/domains/cluster_actors/actor.rs
- duva/src/domains/cluster_actors/hash_ring.rs
- duva/src/domains/cluster_actors/hash_ring/migration_task.rs
- duva/src/presentation/clients/controller.rs
`keys` operation is required for partitioning - which is `O(n)` operation but still okay as migration rarely happens
> feat: revisit keys for reusability

- duva/src/domains/cluster_actors/actor.rs
- duva/src/domains/cluster_actors/actor/tests/partitionings.rs
Previously, both leaders and replicas would initiate migration tasks when receiving hash ring updates, violating the leader-follower principle and potentially causing coordination conflicts and race conditions.
Refactored `maybe_update_hashring()` to differentiate between leader and replica behavior:
- Only update the local hash ring for routing decisions
- Do not initiate any migration tasks
- Wait for leader to coordinate all migrations
- Create migration plans by comparing old vs new hash rings
- Update hash ring after migration planning (fixes critical bug)
- Coordinate all migration tasks across the cluster
- **Fixed critical bug**: Hash ring was being updated too early for leaders, preventing proper migration task creation, closed #613 
- **Improved distributed systems design**: …
> feat: Separate leader and replica responsibilities in hash ring updates

- duva/src/domains/cluster_actors/actor.rs
- duva/src/domains/cluster_actors/actor/tests/cluster_managements.rs
- duva/src/domains/cluster_actors/actor/tests/elections.rs
- duva/src/domains/cluster_actors/actor/tests/mod.rs
- duva/src/domains/cluster_actors/actor/tests/partitionings.rs
- duva/src/domains/cluster_actors/hash_ring.rs
- duva/src/domains/cluster_actors/hash_ring/tests/add_and_remove.rs
- duva/src/domains/cluster_actors/hash_ring/tests/migration.rs
- duva/src/domains/cluster_actors/hash_ring/tests/mod.rs
- duva/src/domains/cluster_actors/service.rs
- duva/src/domains/peers/peer.rs
- duva/src/domains/query_io.rs
This PR refactors the hashring implementation to make it more robust and feature-rich in a multi-shard and multi-replica environment. The primary goal is to ensure that the hashring is always aware of the current shard leaders and that updates to the ring are handled in an idempotent manner. This is crucial for maintaining consistency and reliability in a distributed system where leadership changes and updates can occur frequently.
- Multi-Replica Hashring Updates: The hashring has been updated to handle scenarios with multiple replicas, ensuring that the system can correctly manage and distribute data across them.
- Cluster Shards: The concept of cluster shards has been introduced or modified, which is a fundamental change in how data is partitioned and managed within the cluster.
- …
> feat: hashring multi shard leader update 

- duva/src/domains/cluster_actors/actor.rs
- duva/src/domains/cluster_actors/actor/tests/cluster_managements.rs
previous: update hash_ring after checking pending requests
after: migration is done → update hash_ring with new ring
> fix: change hash ring update after migration done

- duva/src/domains/cluster_actors/actor.rs
- Fix hash_ring update logic when there is no migration plan during cluster meet.
- Remove duplicated mget route which had early return
> fix: hash_ring update logic when cluster meet

- duva/src/domains/cluster_actors/actor.rs
- duva/src/domains/cluster_actors/actor/tests/cluster_managements.rs
- duva/src/domains/cluster_actors/actor/tests/elections.rs
- duva/src/domains/cluster_actors/actor/tests/mod.rs
- duva/src/domains/cluster_actors/actor/tests/partitionings.rs
- duva/src/domains/cluster_actors/actor/tests/replications.rs
- duva/src/domains/cluster_actors/command.rs
- duva/src/domains/cluster_actors/consensus/log.rs
- duva/src/domains/cluster_actors/hash_ring/migration_task.rs
- duva/src/domains/cluster_actors/replication.rs
- duva/src/domains/peers/command.rs
- duva/src/domains/peers/connections/connection_types.rs
- duva/src/domains/peers/connections/inbound/stream.rs
- duva/src/domains/peers/connections/outbound/stream.rs
- duva/src/domains/peers/peer.rs
- duva/src/domains/peers/service.rs
- duva/src/lib.rs
- duva/src/presentation/clusters/communication_manager.rs
- duva/src/types.rs
- test: send SchedulerMessage::SendBatchAck  #712 
- enum comparison on message
- `Helper` added
- `Callback` added
> refactor: make cluster command eq check evaluatable

- Cargo.lock
- duva/Cargo.toml
- duva/src/domains/caches/cache_objects/mod.rs
- duva/src/domains/caches/cache_objects/types/mod.rs
- duva/src/domains/caches/cache_objects/types/quicklist.rs
- duva/src/domains/caches/cache_objects/value.rs
1. Superior Memory Efficiency 
This is the primary reason for choosing a quick list. Instead of thousands of small memory allocations, we have a much smaller number of larger node allocations. By packing many elements side-by-side into a single zip list, we drastically reduce the per-element memory overhead.
For a database storing millions of list entries, this translates to a significantly smaller memory footprint.
2. Excellent Amortized Performance
While a push or pop isn't always a O(1) operation, its performance is exceptional in practice.
- When a node at the head or tail is not full: An LPUSH or RPUSH simply adds an element to that node's internal Ziplist. This is extremely fast.
- When a node is full: We simply create a new node and add it to the list. This small, one-time cost is …
> feat: quick list operation 

- duva-client/src/controller.rs
- duva/src/domains/caches/actor.rs
- duva/src/domains/caches/cache_manager.rs
- duva/src/domains/caches/command.rs
- duva/src/domains/caches/lru_cache.rs
- duva/src/domains/caches/service.rs
- duva/src/domains/operation_logs/operation.rs
- duva/src/presentation/clients/controller.rs
- duva/src/presentation/clients/request.rs
- duva/tests/client_ops/mod.rs
- duva/tests/client_ops/test_lpop.rs
This pull request introduces the LPOP command, which removes and returns one or more elements from the head (left side) of a list.
The implementation is integrated throughout the system, from client request parsing to the core cache logic.
Command Parsing: The client request parser now recognizes the command. The count argument is optional and defaults to 1 as follows
```
LPOP <key> [count] 
```
Cache Logic:
The CacheActor contains the core `LPOP` logic. It removes the list from the cache, pops the specified number of elements, and places the list back in the cache if it's not empty.
It correctly handles cases where the key does not exist or the list becomes empty, returning a nil or empty array response.
Write Operation: `LPOP` is treated as a write request, ensuring it is logged in the …
> feat: lpop 

- duva/src/domains/caches/actor.rs
- duva/src/domains/caches/cache_manager.rs
- duva/src/domains/caches/command.rs
- duva/src/domains/caches/service.rs
- duva/src/presentation/clients/controller.rs
- duva/src/presentation/clients/request.rs
- duva/tests/client_ops/mod.rs
- duva/tests/client_ops/test_rpushx.rs
> feat: rpushx

- duva-client/src/broker/mod.rs
- duva/src/domains/cluster_actors/command.rs
- duva/src/domains/operation_logs/operation.rs
- duva/src/domains/query_io.rs
- duva/src/domains/saves/endec/decoder.rs
- duva/src/domains/saves/endec/mod.rs
- duva/src/presentation/clients/controller.rs
- duva/src/presentation/clients/request.rs
- duva/src/presentation/clients/stream.rs
- duva/tests/common.rs
- unify milliseconds type to i64 from u64: in the code, every place converting u64 to DateTime, we did the i64 type conversion, which is unnecessary.
- now ClientAction have `expires_at` (timestamp in milliseconds). Previously, it was DateTime<Utc>: If we had DateTime<Utc>, cannot convert to bincode
- Serialize ClientAction with bincode inside SessionRequest so that Server doesn’t need to parse user input directly
Resolves: #755
> refactor: serialize ClientAction in SessionRequest

- duva/src/domains/cluster_actors/actor.rs
- duva/src/domains/cluster_actors/command.rs
- duva/src/domains/cluster_actors/service.rs
When eager rebalancing is requested, there is a chance that non-coordinating node is not yet aware of joining node and migration fails as it hasn't established connections. 
We figured that this is general problem for "event on cluster join" 
Considering how actor guarantees the message consumption order while providing asynchrony, 
I had to figure out background task that start working upon certain kind of callback chain. 
Connection establishment requires handshakes and if it is not done in the background, actor will just hang due to synchronous back-and-forth communication where one is waiting for the other to send the next message while the other is doing the same - canonical example of deadlock
Upon completion on connection, we also need to conditionally activate cluster sync - which …
> feat: event trigger on peer discovery

- duva-client/src/cli/editor/completion.rs
> chore: simplify completion

- duva/src/domains/cluster_actors/actor.rs
- duva/src/domains/cluster_actors/actor/tests/replications.rs
- duva/src/domains/cluster_actors/service.rs
- duva/tests/replication_ops/mod.rs
- duva/tests/replication_ops/test_leader_election.rs
- duva/tests/replication_ops/test_leader_election_twice.rs
- duva/tests/replication_ops/test_set_twice_after_election.rs
Here is the precise sequence of events that leads to the malformed HeartBeat being sent:
1. Node A is Leader: Node A is the established leader. Its self.replication.role is ReplicationRole::Leader.
2. Heartbeat is Queued: The HeartBeatScheduler, running in leader mode, fires its timer. It sends a SchedulerMessage::SendAppendEntriesRPC message into the ClusterActor's message queue. This message is now waiting to be processed.
3. A Higher Term Appears: Before the actor processes the SendAppendEntriesRPC message, it receives a different message from another peer—for example, a RequestVote from a candidate in a higher election term.
4. Leader Steps Down: When processing this new message, your code correctly detects the higher term. This causes the leader to step down by calling a function …
> fix: election failure due to scheduler synchronization

- duva/src/domains/caches/cache_objects/types/quicklist.rs
- Fixed unsafe tail offset calculation in Ziplist::rpop() - replaced unwrap_or(0)
with proper find_tail_offset() fallback
- Improved compression logic - raised compression threshold from 48→64 bytes with
better space savings requirement (25% minimum)
- Enhanced decompression - fixed ziplist reconstruction during decompression to
properly restore data and tail offsets
- Better bounds checking in lset() - added proper negative index validation
- Optimized compression criteria - only compress nodes with >128 bytes, multiple
entries, and ensure 25% space savings
- Fixed node pooling - use NodeData::default() for consistent state reset
> chore: bound checker on quicklist
